### ISSUE TITLE
French translation team

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/french#2]
Ideally a language team should have at least two members, s.t. someone else can help to review or work on the French translation.

Maybe @p0nce, @gchatelet, @opisano, @Preovaleo, or @abulmo want to join the D translation team and help @llaine?

(See https://github.com/stonemaster/dlang-tour/issues/132 for background details)

**Comment by llaine** [comment]
Would be great!!

**Comment by opisano** [comment]
Sure, I can help reviewing.

**Comment by ghost** [comment]
We're five now.
